// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using musicwithfriends.Models;

namespace musicwithfriends.Migrations
{
    [DbContext(typeof(musicwithfriendsContext))]
    [Migration("20181201234456_migration7")]
    partial class migration7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("musicwithfriends.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("musicwithfriends.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileLocation");

                    b.Property<int>("RoomId");

                    b.Property<byte[]>("SongData");

                    b.Property<string>("Title");

                    b.HasKey("SongId");

                    b.HasIndex("RoomId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("musicwithfriends.Models.Song", b =>
                {
                    b.HasOne("musicwithfriends.Models.Room", "Room")
                        .WithMany("Songs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
